services:
  # backend:
  #   container_name: image-smith
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   networks:
  #     - image-smith-networks
  #   depends_on:
  #     - db
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health-check"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  db:
    image: postgres:17
    container_name: image-smith-postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/mysql
    networks:
      - image-smith-networks
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  image-smith-networks:
    driver: bridge